### PR TITLE
Handle containers and init containers without information loss

### PR DESCRIPTION
**Pull request by elioengcomp**

### CODE REVIEW

**Comment by jainishshah17** [comment]
@elioengcomp Do we need similar logic in `validateAdmissionReviewHandler` ?

**Comment by elioengcomp** [comment]
Yes. Good point. I forgot about it since I'm not using it.

**Comment by jainishshah17** [comment]
@elioengcomp Can you please add it.

**Comment by elioengcomp** [comment]
Yes.

**Comment by elioengcomp** [comment]
@jainishshah17 can you review it again?

**Comment by jainishshah17** [comment]
@elioengcomp LGTM.

**Pull request merged**
